[tool.poetry]
name = "Swing music player"
version = "0.1.0"
description = ""
authors = ["geoffrey45 <geoffreymungai45@gmail.com>"]

[tool.poetry.dependencies]
python = ">=3.10"
Flask = "^2.0.2"
Flask-Cors = "^3.0.10"
requests = "^2.27.1"
watchdog = "^2.2.0"
gunicorn = "^20.1.0"
Pillow = "^9.0.1"
"colorgram.py" = "^1.2.0"
tqdm = "^4.64.0"
rapidfuzz = "^2.13.7"
tinytag = "^1.8.1"
hypothesis = "^6.56.3"
pytest = "^7.1.3"
pylint = "^2.15.5"
Unidecode = "^1.3.6"
pyinstaller = "^5.7.0"

[tool.poetry.dev-dependencies]
black = {version = "^22.6.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[pytest]
console_output_style = "classic"
testpaths = "tests"
